### ISSUE TITLE
Add to DiffEqDocs?

### ISSUE THREAD

**Issue by ChrisRackauckas** [nathanaelbosch/ProbNumDiffEq.jl#12]
It would be good to add these methods to DiffEqDocs in some way.

**Comment by nathanaelbosch** [comment]
Sure, that would be great! I had already planned on working on the package documentation in the next weeks. How do you imagine having these methods in the SciML documentation? I imagine the minimal thing would be to include them in Sover Algorithms / ODE Solvers. But if it makes sense it would of course also be great for us to have a full page on probabilistic numerical solvers somewhere.

**Comment by ChrisRackauckas** [comment]
Yes, I was thinking to get them in that spot and then link this repo for more information.

**Comment by nathanaelbosch** [comment]
So it would then be referenced similarly to e.g. TaylorIntegration.jl, under "Full list of Methods" in "ODE Solvers", right? That seems doable without too much effort (no tutorial to write or anything). Should I just open a PR to DiffEqDocs.jl?

**Comment by ChrisRackauckas** [comment]
Yup that is where it would go. We probably will want to expand in the UQ section too, but that can happen later.

**Comment by nathanaelbosch** [comment]
Great! There are a few things I'd still like to get done before going a bit more public with this package, but after that (next week I hope) I'll open a PR.

**Comment by nathanaelbosch** [comment]
Closed in https://github.com/SciML/DiffEqDocs.jl/pull/439
