### ISSUE TITLE
Updates for OrdinaryDiffEq split

### ISSUE THREAD

**Issue by ChrisRackauckas** [nathanaelbosch/ProbNumDiffEq.jl#322]
A few changes will need to be made:

* Change to depending on OrdinaryDiffEqCore
* Add `get_fsalfirstlast`overloads for the cache that give what the fsalfirst/fsallast pointers and remove them from the initialize! function (see https://github.com/SciML/OrdinaryDiffEq.jl/pull/2390)

**Comment by nathanaelbosch** [comment]
#325 implements `get_fsalfirstlast`, but in the minimal way to just fix the current installation errors by overloading
```julia
OrdinaryDiffEq.get_fsalfirstlast(cache::EKCache, rate_prototype) = nothing, nothing
 ```
 I also had `OrdinaryDiffEq.isfsal(::AbstractEK) = false` in my code for a while, so I'm a bit suprised to even run into this issue?
 
 Other then that I will make sure to move over to OrdinaryDiffEqCore as soon as I find the time, and I will update this thread whenever I run into some issues. Thanks again for opening this!

**Comment by ChrisRackauckas** [comment]
> I also had OrdinaryDiffEq.isfsal(::AbstractEK) = false in my code for a while, so I'm a bit suprised to even run into this issue?

We should create a generic fallback for this case.

**Comment by nathanaelbosch** [comment]
Thanks a lot for the PR #326!
